apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-load
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-load
  template:
    metadata:
      labels:
        app: spring-boot-load
    spec:
      containers:
        - name: spring-boot-load
          image: asia-northeast3-docker.pkg.dev/ictgcp001/my-repo/spring:version2
          imagePullPolicy: Always
          ports:
            - protocol: TCP
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-load
  labels:
    app: spring-boot-load
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: spring-boot-load
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-load
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-boot-load
                port:
                  number: 8080

